scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 'otel-collector:9090'
  - job_name: app
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'agent-sennser:8080'