version: '3'

services:
  agent-sennser:
    image: agent-sennser
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    privileged: true

  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    image: grafana/grafana:11.3.0
    container_name: grafana
    volumes:
      - ./config/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

    ports:
      - 3000:3000
